USE [FitnessData]
GO

/****** Object:  Table [dim].[YearType]    Script Date: 5/30/2025 1:29:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dim].[YearType](
	[YearID] [int] IDENTITY(300,1) NOT NULL,
	[YearType] [bigint] NULL,
 CONSTRAINT [pk_YearType] PRIMARY KEY CLUSTERED 
(
	[YearID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

